version: '3'
networks: 
  db-data-net:
    driver: bridge
services:
  pythoapp:
    image: pythonapp:1.0
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pythonapp
    ports:
      - "8080:8080"
    environment:
      - ENV=local
      - DATABASE_URL=mysql://app_user:1234@mysql:3306/app_db
    networks:
      - db-data-net
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - db-data-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db-data:
    driver: local

